### ISSUE TITLE
Image save method

### ISSUE THREAD

**Issue by MirandaTilton** [jkhseo/Keras-Vis#3]
We're getting the following error:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TclError: couldn't connect to display ":0"

Susan's suggestion is that you should use a different save method that doesn't require X

**Comment by jkhseo** [comment]
I think I might've fixed it. Can you try it again to see if it works?

**Comment by MirandaTilton** [comment]
It's displaying the images now. They look great! :)

![image](https://user-images.githubusercontent.com/35343189/53531406-d268fc80-3ab8-11e9-8485-934cf645b0e8.png)

**Comment by jkhseo** [comment]
Awesome!
